# Site settings
title: Nicolas Deffieux
email: nicolas@deffieux.eu
description: Intro text here.
baseurl: "/ndef" # the subpath of your site, e.g. /blog
url: "https://jlberryhill.github.io" # the base hostname & protocol for your site
author: Nicolas Deffieux
street_address: 
city: Paris
state: 
zip_code: 
country: France
phone: 

icon: fa-power-off # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/nicolasdeffieux/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
style: compressed
